# Form implementation generated from reading ui file 'ai_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import wikipedia
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 760)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/assistant.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chat_show = QtWidgets.QTextBrowser(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.chat_show.setFont(font)
        self.chat_show.setObjectName("chat_show")
        self.verticalLayout_3.addWidget(self.chat_show)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(471, 141))
        self.stackedWidget.setMaximumSize(QtCore.QSize(471, 141))
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_box = QtWidgets.QWidget()
        self.main_box.setObjectName("main_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.keybord_btn = QtWidgets.QPushButton(parent=self.main_box)
        self.keybord_btn.setEnabled(True)
        self.keybord_btn.setMaximumSize(QtCore.QSize(111, 71))
        self.keybord_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.keybord_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/keyboard-svgrepo-com.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.keybord_btn.setIcon(icon1)
        self.keybord_btn.setIconSize(QtCore.QSize(60, 60))
        self.keybord_btn.setObjectName("keybord_btn")
        self.horizontalLayout.addWidget(self.keybord_btn)
        self.mic_btn = QtWidgets.QToolButton(parent=self.main_box)
        self.mic_btn.setMaximumSize(QtCore.QSize(111, 71))
        self.mic_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.mic_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/mic.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.mic_btn.setIcon(icon2)
        self.mic_btn.setIconSize(QtCore.QSize(60, 60))
        self.mic_btn.setObjectName("mic_btn")
        self.horizontalLayout.addWidget(self.mic_btn)
        self.setting_btn = QtWidgets.QPushButton(parent=self.main_box)
        self.setting_btn.setMaximumSize(QtCore.QSize(121, 71))
        self.setting_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.setting_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.setting_btn.setIcon(icon3)
        self.setting_btn.setIconSize(QtCore.QSize(60, 60))
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout.addWidget(self.setting_btn)
        self.stackedWidget.addWidget(self.main_box)
        self.send_mess = QtWidgets.QWidget()
        self.send_mess.setObjectName("send_mess")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.send_mess)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_query = QtWidgets.QLineEdit(parent=self.send_mess)
        self.text_query.setMinimumSize(QtCore.QSize(331, 41))
        self.text_query.setMaximumSize(QtCore.QSize(331, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.text_query.setFont(font)
        self.text_query.setObjectName("text_query")
        self.horizontalLayout_2.addWidget(self.text_query)
        self.send_btn = QtWidgets.QPushButton(parent=self.send_mess)
        self.send_btn.setMaximumSize(QtCore.QSize(51, 41))
        self.send_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.send_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/send.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.send_btn.setIcon(icon4)
        self.send_btn.setIconSize(QtCore.QSize(50, 40))
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_2.addWidget(self.send_btn)
        self.stackedWidget.addWidget(self.send_mess)
        self.setting_box = QtWidgets.QWidget()
        self.setting_box.setObjectName("setting_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.setting_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.set_lang = QtWidgets.QWidget(parent=self.setting_box)
        self.set_lang.setMaximumSize(QtCore.QSize(16777215, 141))
        self.set_lang.setObjectName("set_lang")
        self.label_2 = QtWidgets.QLabel(parent=self.set_lang)
        self.label_2.setGeometry(QtCore.QRect(9, 9, 368, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.eng_rad_btn = QtWidgets.QRadioButton(parent=self.set_lang)
        self.eng_rad_btn.setGeometry(QtCore.QRect(9, 65, 368, 22))
        self.eng_rad_btn.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.eng_rad_btn.setFont(font)
        self.eng_rad_btn.setObjectName("eng_rad_btn")
        self.vn_rad_btn = QtWidgets.QRadioButton(parent=self.set_lang)
        self.vn_rad_btn.setGeometry(QtCore.QRect(9, 93, 368, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.vn_rad_btn.setFont(font)
        self.vn_rad_btn.setObjectName("vn_rad_btn")
        self.jap_rad_btn = QtWidgets.QRadioButton(parent=self.set_lang)
        self.jap_rad_btn.setGeometry(QtCore.QRect(9, 37, 368, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.jap_rad_btn.setFont(font)
        self.jap_rad_btn.setObjectName("jap_rad_btn")
        self.horizontalLayout_3.addWidget(self.set_lang)
        self.save_set_btn = QtWidgets.QPushButton(parent=self.setting_box)
        self.save_set_btn.setMaximumSize(QtCore.QSize(61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.save_set_btn.setFont(font)
        self.save_set_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_set_btn.setStyleSheet("#save_set_btn{\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.save_set_btn.setObjectName("save_set_btn")
        self.horizontalLayout_3.addWidget(self.save_set_btn)
        self.stackedWidget.addWidget(self.setting_box)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # cài đặt mặc định
        self.vn_rad_btn.setChecked(True)
        wikipedia.set_lang(self.language_set())

        # chuyển stackedWidget
        self.keybord_btn.clicked.connect(self.show_mess)
        self.setting_btn.clicked.connect(self.show_setting_box)
        self.save_set_btn.clicked.connect(self.save_setting)
        self.send_btn.clicked.connect(self.send_message)

        # radion check
        self.vn_rad_btn.clicked.connect(self.vn_btn_clicked)
        self.eng_rad_btn.clicked.connect(self.eng_btn_clicked)
        self.jap_rad_btn.clicked.connect(self.jap_btn_clicked)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Ngôn ngữ"))
        self.eng_rad_btn.setText(_translate("MainWindow", "English"))
        self.vn_rad_btn.setText(_translate("MainWindow", "Vietnamese"))
        self.jap_rad_btn.setText(_translate("MainWindow", "Japanese"))
        self.save_set_btn.setText(_translate("MainWindow", "Save"))

    # chuyển stackedWidget
    def show_main_box(self):
        self.stackedWidget.setCurrentIndex(0)
    def show_mess(self):
        self.stackedWidget.setCurrentIndex(1)
    def show_setting_box(self):
        self.stackedWidget.setCurrentIndex(2)
    
    # radion click
    def vn_btn_clicked(self):
        self.vn_rad_btn.setChecked(True)
        self.eng_rad_btn.setChecked(False)
        self.jap_rad_btn.setChecked(False)

    def eng_btn_clicked(self):
        self.eng_rad_btn.setChecked(True)
        self.vn_rad_btn.setChecked(False)
        self.jap_rad_btn.setChecked(False)

    def jap_btn_clicked(self):
        self.jap_rad_btn.setChecked(True)
        self.vn_rad_btn.setChecked(False)
        self.eng_rad_btn.setChecked(False)

# cài đặt ngôn ngữ
    def language_set(self):
        if self.vn_rad_btn.isChecked():
            language = 'vi'
        elif self.eng_rad_btn.isChecked():
            language = 'en'
        else:
            language = 'ja'

        return language
    
    # lưu cài đặt
    def save_setting(self):
        wikipedia.set_lang(self.language_set())
        self.show_main_box()   

    # nhập và gửi tin nhắn
    def send_message(self):
        query = self.text_query.text()
        self.chat_show.append("You: " + query)
        self.show_main_box()
        self.text_query.clear()
        # self.assistant(query) 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
